name: CI
on:
  - push 
jobs:
  MPIPETScCommTests:
   runs-on: ubuntu-latest
   env:
     JULIA_MPI_BINARY: "system"
   steps:
     - uses: actions/checkout@v2
     - uses: julia-actions/setup-julia@v1
       with:
         version: 1.6
         arch: x64 
     - name: Install p4est/petsc dependencies
       run: |
           sudo apt-get update 
           sudo apt-get install -y wget gfortran g++ openmpi-bin libopenmpi-dev
     - run: julia --project=. --color=yes -e 'using Pkg; Pkg.instantiate()'
     - run: julia --project=. -e 'using Pkg; pkg"instantiate"'
     - run: julia --project=. -e 'using Pkg; pkg"precompile"'
     - run: julia --project=. --color=yes test.jl  
